"""add matched_at to watchlist_matches

Revision ID: e4271581a676
Revises: 63c5be38eaf2
Create Date: 2026-02-25 14:10:27.444006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4271581a676'
down_revision: Union[str, Sequence[str], None] = '63c5be38eaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_matches', sa.Column('matched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_matches', 'matched_at')
    # ### end Alembic commands ###
